munin:
  fixedDelay: ${SCHEDULER_TIME:30000}

spring:
  datasource:
    password: ${DB_USER:""}
    url: ${DB_URL:localhost}
    username: ${DB_USER:root}
    driver-class-name: org.postgresql.Driver
pepe_endpoint: ${PEPE_ENDPOINT:localhost:80000}
