build:
  project: '@project.artifactId@'
  timestamp: '@timestamp@'
  version: '@project.version@'

spring:
  datasource:
    driver-class-name: ${DB_MUNIN_DRIVER:org.h2.Driver}
    url: ${DB_MUNIN_URL:jdbc:h2:mem:test;MODE=MySQL}
    username: ${DB_MUNIN_USER:sa}
    password: ${DB_MUNIN_PASSWORD:}
  jpa:
    show-sql: ${DB_MUNIN_SHOWSQL:false}
    hibernate:
      ddl-auto: ${DB_MUNIN_DDL:create}
    properties:
      hibernate:
        dialect: ${DB_MUNIN_DIALECT:org.hibernate.dialect.H2Dialect}
  pid:
    file: ${PID_FILE:/tmp/pepe-chapolin.pid}

pepe:
  logging:
    tags: ${LOGGING_TAGS:default}
  api:
    endpoint: ${PEPE_ENDPOINT:http://127.0.0.1:8000}
  keystone:
    url: ${KEYSTONE_URL:http://127.0.0.1:5000/v3}
    domain: ${KEYSTONE_DOMAIN:default}
  munin:
    source: ${MUNIN_SOURCE:munin}
    min-sched-delay: ${MUNIN_MIN_SCHED_DELAY:10000}
    jdbc:
      register-sched-delay: ${MUNIN_JDBC_REGISTER_DELAY:20000}
      datasource-cache-ttl: ${MUNIN_DATASOURCE_CACHE_TTL:120000}
      jar-local-dir: ${MUNIN_JAR_LOCAL_DIR:/tmp}
  secret: ${PEPE_SECRET:mysecret}

server:
  port: ${SERVER_PORT:8000}

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost}
  allowed-methods: ${CORS_METHODS:GET,POST,DELETE,PATCH,PUT,HEAD,OPTIONS,TRACE,CONNECT}