spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pepe}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:""}

pepe:
  logging:
    tags: default
  api:
    endpoint: ${PEPE_ENDPOINT:http://localhost:8000}
  keystone:
    url: ${KEYSTONE_URL:""}
    user: ${KEYSTONE_USER:""}
    password: ${KEYSTONE_PASSWORD:""}
    identifier: ${KEYSTONE_IDENTIFIER:""}
  munin:
    query: ${MUNIN_QUERY_WORKER:""}
    source: ${MUNIN_SOURCE:""}
    fixedDelay: ${SCHEDULER_TIME:30000}
    trigger_name: ${MUNIN_TRIGGER:acs-collector}